paint_board-8: Created component footer and added outside fonts
KoTuK2306/paint_board pull request #11
Opened 2021-02-02 15:08 UTC by KoTuK2306

2021-02-02 16:35 UTC, SMPlay requested changes

2021-02-02 16:35 UTC, SMPlay commented on src/components/footer/footer.style.tsx
> +import '../../fonts/Montserrat/Montserrat.css';
just `fonts/...`

2021-02-02 16:35 UTC, SMPlay commented on src/components/footer/footer.style.tsx
> +import { Colors } from '../../style-constants';
just `style-constants`

2021-02-02 16:35 UTC, SMPlay commented on src/components/footer/footer.style.tsx
> +    fontFamily: 'Montserrat-Regular',
move right after padding

2021-02-02 16:35 UTC, SMPlay commented on src/components/footer/footer.tsx
> +      <p className={classes.footerText}>© Paint board 2021</p>
set dynamic year

2021-02-02 16:35 UTC, SMPlay commented on src/fonts/Montserrat/Montserrat.css
> +  font-family: 'Montserrat-Bold';
create enum with all fonts and set default `sans-serif`

2021-02-02 16:35 UTC, SMPlay commented on src/components/footer/footer.style.tsx
> +import '../../fonts/Montserrat/Montserrat.css';
move this import to index.css

2021-02-02 18:02 UTC, SMPlay approved these changes

2021-02-02 18:06 UTC, IliaSolovev requested changes

2021-02-02 18:06 UTC, IliaSolovev commented on .eslintrc
> +    "no-shadow": "off",
delete this rules

2021-02-02 18:06 UTC, IliaSolovev commented on .eslintrc
> +    "@typescript-eslint/no-shadow": "error",
and this

2021-02-02 18:06 UTC, IliaSolovev commented on src/components/footer/footer.tsx
> +      <p className={classes.footerText}>© Paint board {new Date().getFullYear()}</p>
```suggestion
      <p className={classes.text}>© Paint board {new Date().getFullYear()}</p>
```

2021-02-03 10:02 UTC, IliaSolovev approved these changes

2021-02-03 10:03 UTC, merged